In [120]:
! pip install pandas

Requirement already satisfied: pandas in D:\Users\OYO\Desktop\Python\datascience\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in D:\Users\OYO\Desktop\Python\datascience\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Users\OYO\Desktop\Python\datascience\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Users\OYO\Desktop\Python\datascience\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in D:\Users\OYO\Desktop\Python\datascience\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### PANDAS 

* Pandas works as a strainer on the data and strains the data out.

In [121]:
import os
import numpy as np
import pandas as pd  ### data ko anayze kregi alias hai ye iske

In [122]:
df=pd.read_csv(r'D:\Users\OYO\Desktop\Python\Used_Bikes.csv')

In [123]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [124]:
df.head()     ### by default 5 starting rows return krta hai

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [125]:
df.head(10)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield

In [126]:
df.tail()

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [127]:
df.tail(15)

,bike_name,price,city,kms_driven,owner,age,power,brand
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32635,Suzuki Zeus 125cc,35000.0,Ahmedabad,11885.0,First Owner,12.0,125.0,Suzuki
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [128]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [129]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [130]:
df['bike_name']

0          TVS Star City Plus Dual Tone 110cc
1                 Royal Enfield Classic 350cc
2                        Triumph Daytona 675R
3                        TVS Apache RTR 180cc
4        Yamaha FZ S V 2.0 150cc-Ltd. Edition
                         ...
32643                  Hero Passion Pro 100cc
32644                    TVS Apache RTR 180cc
32645                Bajaj Avenger Street 220
32646               Hero Super Splendor 125cc
32647                      Bajaj Pulsar 150cc
Name: bike_name, Length: 32648, dtype: str

In [131]:
df['brand']

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [132]:
df[['brand']] ## ab ye proper ddataframe ke format mai hai

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [133]:
df[['bike_name','price']]

                                  bike_name     price
0        TVS Star City Plus Dual Tone 110cc   35000.0
1               Royal Enfield Classic 350cc  119900.0
2                      Triumph Daytona 675R  600000.0
3                      TVS Apache RTR 180cc   65000.0
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0
...                                     ...       ...
32643                Hero Passion Pro 100cc   39000.0
32644                  TVS Apache RTR 180cc   30000.0
32645              Bajaj Avenger Street 220   60000.0
32646             Hero Super Splendor 125cc   15600.0
32647                    Bajaj Pulsar 150cc   22000.0

[32648 rows x 2 columns]

In [134]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [135]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [136]:
df['city'].unique()

<StringArray>
[   'Ahmedabad',        'Delhi',    'Bangalore',       'Mumbai',
       'Kalyan',    'Faridabad',       'Mettur',    'Hyderabad',
      'Kaithal',      'Gurgaon',
 ...
  'Bhubaneswar',      'Raiganj', 'Bhilai Nagar',       'Baloda',
     'Anantnag',   'Berhampore',      'Silvasa',       'Hospet',
        'Palai',        'Sidhi']
Length: 443, dtype: str

In [137]:
df['brand'].nunique()  ### no. of unique value

23

In [138]:
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [139]:
import pandas as pd
df.duplicated() ### dupiicate values pe true deta hai

0        False
1        False
2        False
3        False
4        False
         ...
32643     True
32644     True
32645     True
32646     True
32647     True
Length: 32648, dtype: bool

In [140]:
df.duplicated().sum() ### ye duplicate ka sum return krta hai

np.int64(25324)

In [141]:
df.drop_duplicates() ###isse permantently drop nhi hui duplicates

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [142]:
df.drop_duplicates(inplace=True) ###isse permantently drop hui duplicates

In [143]:
df.duplicated().sum()

np.int64(0)

In [144]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [145]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [146]:
df.dropna(inplace=True) ##null values ko permentately dl kr deta hai

In [147]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [148]:
# y=mx+c   linear regression

In [149]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [150]:
owner_dict={
    'First Owner': 1, 'Second Owner': 2, 'Third Owner': 3, 'Fourth Owner Or More':4
}

In [151]:
# df['owner']=df['owner'].map(owner_dict) ###map functions ka kaammapping kra hai hai jo js mai present rhte hai

In [152]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [153]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [154]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [155]:
## df.drop('city', axis=1, inplace=True)

In [156]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [157]:
df.drop(['price','bike_name'], axis=1,inplace=True)

In [158]:
df

           city  kms_driven        owner  age  power            brand
0     Ahmedabad     17654.0  First Owner  3.0  110.0              TVS
1         Delhi     11000.0  First Owner  4.0  350.0    Royal Enfield
2         Delhi       110.0  First Owner  8.0  675.0          Triumph
3     Bangalore     16329.0  First Owner  4.0  180.0              TVS
4     Bangalore     10000.0  First Owner  3.0  150.0           Yamaha
...         ...         ...          ...  ...    ...              ...
9362      Delhi     48587.0  First Owner  8.0  150.0             Hero
9369  Bangalore     60000.0  First Owner  9.0  220.0            Bajaj
9370    Jodhpur      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  Hyderabad     21300.0  First Owner  4.0  400.0            Bajaj
9372  Hyderabad      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [159]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [160]:
brand_dict={
     'TVS':1,   'Royal Enfield':2,         'Triumph':3,          'Yamaha':4,
           'Honda':5,            'Hero':6,           'Bajaj':7,          'Suzuki':8,
         'Benelli':9,             'KTM':10,        'Mahindra':11,        'Kawasaki':12,
          'Ducati':13,         'Hyosung':14, 'Harley-Davidson':15,            'Jawa':16,
             'BMW':17,          'Indian':18,         'Rajdoot':19,             'LML':20,
           'Yezdi':21,              'MV':22,           'Ideal':23
}

In [161]:
# df['brand']=df['brand'].map(brand_dict)

In [162]:
df

           city  kms_driven        owner  age  power            brand
0     Ahmedabad     17654.0  First Owner  3.0  110.0              TVS
1         Delhi     11000.0  First Owner  4.0  350.0    Royal Enfield
2         Delhi       110.0  First Owner  8.0  675.0          Triumph
3     Bangalore     16329.0  First Owner  4.0  180.0              TVS
4     Bangalore     10000.0  First Owner  3.0  150.0           Yamaha
...         ...         ...          ...  ...    ...              ...
9362      Delhi     48587.0  First Owner  8.0  150.0             Hero
9369  Bangalore     60000.0  First Owner  9.0  220.0            Bajaj
9370    Jodhpur      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  Hyderabad     21300.0  First Owner  4.0  400.0            Bajaj
9372  Hyderabad      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [163]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [164]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        7324 non-null   str
 1   kms_driven  7324 non-null   float64
 2   owner       7324 non-null   str
 3   age         7324 non-null   float64
 4   power       7324 non-null   float64
 5   brand       7324 non-null   str
dtypes: float64(3), str(3)
memory usage: 400.5 KB

In [165]:
df

           city  kms_driven        owner  age  power            brand
0     Ahmedabad     17654.0  First Owner  3.0  110.0              TVS
1         Delhi     11000.0  First Owner  4.0  350.0    Royal Enfield
2         Delhi       110.0  First Owner  8.0  675.0          Triumph
3     Bangalore     16329.0  First Owner  4.0  180.0              TVS
4     Bangalore     10000.0  First Owner  3.0  150.0           Yamaha
...         ...         ...          ...  ...    ...              ...
9362      Delhi     48587.0  First Owner  8.0  150.0             Hero
9369  Bangalore     60000.0  First Owner  9.0  220.0            Bajaj
9370    Jodhpur      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  Hyderabad     21300.0  First Owner  4.0  400.0            Bajaj
9372  Hyderabad      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [166]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        7324 non-null   str
 1   kms_driven  7324 non-null   float64
 2   owner       7324 non-null   str
 3   age         7324 non-null   float64
 4   power       7324 non-null   float64
 5   brand       7324 non-null   str
dtypes: float64(3), str(3)
memory usage: 400.5 KB

In [167]:
obj_val=df.select_dtypes(include='O') ###ye character values ko nikallne ke kaam aata hai

C:\Users\OYO\AppData\Local\Temp\ipykernel_10676\1626187310.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_val=df.select_dtypes(include='O') ###ye character values ko nikallne ke kaam aata hai

In [168]:
obj_val

           city        owner            brand
0     Ahmedabad  First Owner              TVS
1         Delhi  First Owner    Royal Enfield
2         Delhi  First Owner          Triumph
3     Bangalore  First Owner              TVS
4     Bangalore  First Owner           Yamaha
...         ...          ...              ...
9362      Delhi  First Owner             Hero
9369  Bangalore  First Owner            Bajaj
9370    Jodhpur  First Owner  Harley-Davidson
9371  Hyderabad  First Owner            Bajaj
9372  Hyderabad  First Owner            Bajaj

[7324 rows x 3 columns]

In [169]:
num_val=df.select_dtypes(exclude='O') ### ye int values ko nikalne ke kaam aata hai

In [170]:
num_val

      kms_driven  age  power
0        17654.0  3.0  110.0
1        11000.0  4.0  350.0
2          110.0  8.0  675.0
3        16329.0  4.0  180.0
4        10000.0  3.0  150.0
...          ...  ...    ...
9362     48587.0  8.0  150.0
9369     60000.0  9.0  220.0
9370      3430.0  4.0  750.0
9371     21300.0  4.0  400.0
9372      7127.0  5.0  220.0

[7324 rows x 3 columns]

In [171]:
complete_data=pd.concat([obj_val,num_val], axis=1) # axis=1(col) axis=0(row)

In [172]:
complete_data

           city        owner            brand  kms_driven  age  power
0     Ahmedabad  First Owner              TVS     17654.0  3.0  110.0
1         Delhi  First Owner    Royal Enfield     11000.0  4.0  350.0
2         Delhi  First Owner          Triumph       110.0  8.0  675.0
3     Bangalore  First Owner              TVS     16329.0  4.0  180.0
4     Bangalore  First Owner           Yamaha     10000.0  3.0  150.0
...         ...          ...              ...         ...  ...    ...
9362      Delhi  First Owner             Hero     48587.0  8.0  150.0
9369  Bangalore  First Owner            Bajaj     60000.0  9.0  220.0
9370    Jodhpur  First Owner  Harley-Davidson      3430.0  4.0  750.0
9371  Hyderabad  First Owner            Bajaj     21300.0  4.0  400.0
9372  Hyderabad  First Owner            Bajaj      7127.0  5.0  220.0

[7324 rows x 6 columns]

In [173]:
import pandas as pd

In [176]:
tvs_brand=df[df['brand']=='TVS']

In [177]:
tvs_under2 = tvs_brand[tvs_brand['age']<=2]

In [178]:
tvs_under2[tvs_under2['kms_driven']<=20000]

           city  kms_driven        owner  age  power brand
193   Hyderabad     16000.0  First Owner  2.0  160.0   TVS
360    Rudrapur      3710.0  First Owner  2.0  160.0   TVS
401       Delhi     10000.0  First Owner  2.0  200.0   TVS
425       Delhi      7000.0  First Owner  2.0  160.0   TVS
511     Gurgaon      7000.0  First Owner  2.0  160.0   TVS
594       Delhi      1050.0  First Owner  2.0  160.0   TVS
664       Delhi      3000.0  First Owner  2.0  160.0   TVS
1097  Bangalore      2500.0  First Owner  2.0  200.0   TVS
1126  Bangalore      1300.0  First Owner  1.0  200.0   TVS
1132     Jaipur       749.0  First Owner  1.0  160.0   TVS
1171     Mumbai      4400.0  First Owner  2.0  310.0   TVS
1318  Hyderabad       530.0  First Owner  2.0  200.0   TVS
1514      Delhi      8000.0  First Owner  2.0  160.0   TVS
1678    Chennai      3100.0  First Owner  2.0  200.0   TVS
1712   Vadodara      3900.0  First Owner  2.0  310.0   TVS
1741      Delhi      2800.0  First Owner  2.0  200.0   TVS
1762      Delhi      2800.0  First Owner  2.0  160.0   TVS
1802    Gurgaon       900.0  First Owner  2.0  180.0   TVS
2325     Mumbai      4500.0  First Owner  2.0  200.0   TVS
2360      Delhi      6000.0  First Owner  2.0  110.0   TVS
2415      Delhi     11496.0  First Owner  2.0  160.0   TVS
3071  Ahmedabad       893.0  First Owner  2.0  160.0   TVS
3333     Mumbai      6821.0  First Owner  2.0  160.0   TVS
3440     Mumbai     14289.0  First Owner  2.0  160.0   TVS
4251  Ahmedabad     12000.0  First Owner  2.0  110.0   TVS
4367  Ghaziabad      2672.0  First Owner  2.0  160.0   TVS
5506      Delhi      1890.0  First Owner  2.0  200.0   TVS
5510  Ghaziabad      3095.0  First Owner  2.0  180.0   TVS
5557      Thane      8120.0  First Owner  2.0  200.0   TVS
5805  Bangalore      4000.0  First Owner  2.0  200.0   TVS
6003      Delhi       900.0  First Owner  2.0  160.0   TVS
6058      Noida      5432.0  First Owner  2.0  310.0   TVS
6571  Faridabad     15228.0  First Owner  2.0  160.0   TVS
6787     Mumbai      7157.0  First Owner  2.0  200.0   TVS
7055  Faridabad      6222.0  First Owner  2.0  100.0   TVS
8883     Mumbai      4442.0  First Owner  2.0  200.0   TVS
9322      Delhi      4020.0  First Owner  2.0  110.0   TVS

In [183]:
df[(df['brand']=='Royal Enfield') & (df['age']<=2) & (df['kms_driven']<=150000)]

              city  kms_driven        owner  age  power          brand
38      Samastipur      4550.0  First Owner  2.0  500.0  Royal Enfield
81     Navi Mumbai      3800.0  First Owner  2.0  650.0  Royal Enfield
139       Vadodara     14000.0  First Owner  2.0  410.0  Royal Enfield
194      Bangalore      4000.0  First Owner  2.0  350.0  Royal Enfield
222   Hamirpur(hp)      7000.0  First Owner  2.0  410.0  Royal Enfield
...            ...         ...          ...  ...    ...            ...
7294        Mumbai      1608.0  First Owner  2.0  350.0  Royal Enfield
7694         Delhi       417.0  First Owner  2.0  500.0  Royal Enfield
8139     Bangalore      4411.0  First Owner  2.0  350.0  Royal Enfield
8192     Ghaziabad     12400.0  First Owner  2.0  350.0  Royal Enfield
8836        Mumbai      1000.0  First Owner  2.0  350.0  Royal Enfield

[61 rows x 6 columns]

In [186]:
df.query("brand=='Royal Enfield' and age <= 2")

              city  kms_driven        owner  age  power          brand
38      Samastipur      4550.0  First Owner  2.0  500.0  Royal Enfield
81     Navi Mumbai      3800.0  First Owner  2.0  650.0  Royal Enfield
139       Vadodara     14000.0  First Owner  2.0  410.0  Royal Enfield
194      Bangalore      4000.0  First Owner  2.0  350.0  Royal Enfield
222   Hamirpur(hp)      7000.0  First Owner  2.0  410.0  Royal Enfield
...            ...         ...          ...  ...    ...            ...
7294        Mumbai      1608.0  First Owner  2.0  350.0  Royal Enfield
7694         Delhi       417.0  First Owner  2.0  500.0  Royal Enfield
8139     Bangalore      4411.0  First Owner  2.0  350.0  Royal Enfield
8192     Ghaziabad     12400.0  First Owner  2.0  350.0  Royal Enfield
8836        Mumbai      1000.0  First Owner  2.0  350.0  Royal Enfield

[61 rows x 6 columns]

In [190]:
df.drop([ 'city'], axis=1,inplace=True)

In [191]:
df

      kms_driven        owner  age  power            brand
0        17654.0  First Owner  3.0  110.0              TVS
1        11000.0  First Owner  4.0  350.0    Royal Enfield
2          110.0  First Owner  8.0  675.0          Triumph
3        16329.0  First Owner  4.0  180.0              TVS
4        10000.0  First Owner  3.0  150.0           Yamaha
...          ...          ...  ...    ...              ...
9362     48587.0  First Owner  8.0  150.0             Hero
9369     60000.0  First Owner  9.0  220.0            Bajaj
9370      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371     21300.0  First Owner  4.0  400.0            Bajaj
9372      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 5 columns]

In [192]:
df.duplicated().sum()

np.int64(459)

In [196]:
df.drop_duplicates(inplace=True)

In [197]:
df.duplicated().sum()

np.int64(0)

In [198]:
df.isnull().sum()

kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [205]:
x=df.drop(['age'],axis=1)

In [206]:
x

      kms_driven        owner  power            brand
0        17654.0  First Owner  110.0              TVS
1        11000.0  First Owner  350.0    Royal Enfield
2          110.0  First Owner  675.0          Triumph
3        16329.0  First Owner  180.0              TVS
4        10000.0  First Owner  150.0           Yamaha
...          ...          ...    ...              ...
9362     48587.0  First Owner  150.0             Hero
9369     60000.0  First Owner  220.0            Bajaj
9370      3430.0  First Owner  750.0  Harley-Davidson
9371     21300.0  First Owner  400.0            Bajaj
9372      7127.0  First Owner  220.0            Bajaj

[6865 rows x 4 columns]

In [207]:
y=df['age']

In [208]:
y

0       3.0
1       4.0
2       8.0
3       4.0
4       3.0
       ...
9362    8.0
9369    9.0
9370    4.0
9371    4.0
9372    5.0
Name: age, Length: 6865, dtype: float64

In [209]:
df.to_csv("clear_bike_data.csv")